name: Check for WordPress releases

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

defaults:
  run:
    working-directory: cron

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '12'
        cache: 'npm'
        cache-dependency-path: 'cron/package-lock.json'
    - run: npm ci
    - name: Check for new WordPress release
      run: npm start
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        TRAVIS_API_KEY: ${{ secrets.TRAVIS_API_KEY }}
