name: Update roots/wordpress composer package

on:
  workflow_dispatch:
  repository_dispatch:
    types: [wordpress-release]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set env vars
      run: |
        echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
        echo "GITHUB_USERNAME=roots-ladybug" >> $GITHUB_ENV
    - name: Create roots/wordpress release
      uses: docker://austinpray/roots-wordpress-updater
      env:
        GITHUB_USERNAME: "roots-ladybug"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
