name: Update roots/wordpress composer package

on:
  workflow_dispatch:
  repository_dispatch:
    types: [wordpress-release]

jobs:
  update:
    permissions:
      actions: write
      contents: write
      repos: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create roots/wordpress release
      uses: docker://austinpray/roots-wordpress-updater
      env:
        GITHUB_USERNAME: "roots-ladybug"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
