name: Versions

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/10 * * * *'

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    outputs:
      tags-matrix: steps.tags-matrix.outputs.tags-matrix
      latest-release: steps.latest-release.outputs.latest-release
    steps:
      - name: Get upstream package name
        id: package
        run: echo "::set-output name=package-name::$(jq -r '.require | map_values(select(. == "self.version")) | keys[]' composer.json)"

      - name: Generate diff of versions arrays
        id: tags-matrix
        run: echo TODO
        # Read GitHub API on current & upstream tags and diff
        # Output: tags-matrix

      - name: Extract latest release
        id: latest-release
        run: echo TODO
        # Semver compare to get the new latest
        # Or sort the array out and get the last value
        # Output: latest-release

  tags:
    name: Tags
    runs-on: ubuntu-latest
    needs:
      - sync
    if: needs.sync.outputs.tags-matrix
    strategy:
      fail-fast: false
      matrix:
        tag: ${{ fromJSON(needs.sync.outputs.tags-matrix) }}
    steps:
      - name: Create a tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ matrix.tag }}
          message: ${{ matrix.tag }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - sync
      - tags
    if: needs.sync.outputs.latest-release
    steps:
      - name: Generate token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Create a release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ steps.generate-token.outputs.token }}
          body: Version ${{ needs.sync.outputs.latest-release }}
          tag_name: ${{ needs.sync.outputs.latest-release }}
